version: '3'

services:
  authentication_database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    volumes:
      - authentication_data:/var/lib/mysql
    networks:
      - authentication_network

  authentication:
    image: authentication
    environment:
      - DATABASE_URL=authentication_database
    depends_on:
      authentication_database:
        condition: service_healthy
    ports:
      - "5000:5000"
    networks:
      - authentication_network

  store_database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    volumes:
      - store_data:/var/lib/mysql
    networks:
      - store_network

  store_init:
    image: store_init
    environment:
      - DATABASE_URL=store_database
    depends_on:
      store_database:
        condition: service_healthy
    networks:
      - store_network

  owner:
    image: owner
    environment:
      - DATABASE_URL=store_database
      - STATISTICS_SERVER_URL=statistics
    depends_on:
      - store_init
    networks:
      - store_network
    ports:
      - "5001:5001"

  customer:
    image: customer
    environment:
      - DATABASE_URL=store_database
    depends_on:
      - store_init
    networks:
      - store_network
    ports:
      - "5002:5002"

  courier:
    image: courier
    environment:
      - DATABASE_URL=store_database
    depends_on:
      - store_init
    networks:
      - store_network
    ports:
      - "5003:5003"

  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      - store_network

  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
      - store_network

  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
      - store_network

  statistics:
    image: statistics
    depends_on: [ spark-master, spark-worker-1, spark-worker-2 ]
    environment:
      - ENABLE_INIT_DAEMON=false
      - DATABASE_URL=store_database
    networks:
      - store_network

volumes:
  authentication_data:
  store_data:

networks:
  authentication_network:
  store_network: